# Generated by Django 5.1.5 on 2025-01-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='year',
            new_name='annee',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='day',
            new_name='jour',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='month',
            new_name='mois',
        ),
    ]
