# Generated by Django 5.1.5 on 2025-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendier', '0002_rename_year_rendezvous_annee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='conseiller_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
