# Generated by Django 5.1.5 on 2025-01-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendier', '0004_alter_rendezvous_conseiller_id_alter_rendezvous_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='conseiller_id',
            new_name='conseiller',
        ),
    ]
